-- 对象拍卖会：独立数据库（不会修改人生拍卖会的 rooms / players / wins）
-- 每人初始资产 25,000,000 元；全部拍品 1,000,000 元起拍；每次至少加 1,000,000 元。
create extension if not exists pgcrypto;

create table if not exists public.love_rooms (
 id text primary key, host_secret text not null, current_lot integer,
 status text not null default 'waiting' check(status in ('waiting','open','closed')),
 current_bid bigint, current_bidder uuid, current_bidder_name text,
 created_at timestamptz not null default now()
);
create table if not exists public.love_players (
 id uuid primary key default gen_random_uuid(), room_id text not null references public.love_rooms(id) on delete cascade,
 name text not null, token text not null, balance bigint not null default 25000000 check(balance>=0),
 active boolean not null default true, joined_at timestamptz not null default now(), unique(room_id,token)
);
create table if not exists public.love_wins (
 id bigint generated by default as identity primary key, room_id text not null references public.love_rooms(id) on delete cascade,
 lot_id integer not null, player_id uuid not null references public.love_players(id) on delete cascade,
 player_name text not null, price bigint not null, created_at timestamptz not null default now(), unique(room_id,lot_id)
);

create or replace function public.love_create_room(p_room_id text,p_host_secret text) returns void language plpgsql security definer set search_path=public as $$
begin if length(p_room_id)<4 or length(p_host_secret)<16 then raise exception 'invalid room'; end if; insert into love_rooms(id,host_secret) values(upper(p_room_id),p_host_secret); end $$;

create or replace function public.love_join_room(p_room_id text,p_name text,p_token text) returns table(player_id uuid,balance bigint) language plpgsql security definer set search_path=public as $$
declare pid uuid; rid text:=upper(p_room_id); begin
 if not exists(select 1 from love_rooms where id=rid) then raise exception '房间不存在'; end if;
 if char_length(trim(p_name))<1 then raise exception '请输入昵称'; end if;
 select p.id into pid from love_players p where p.room_id=rid and p.token=p_token limit 1;
 if pid is not null then update love_players set name=left(trim(p_name),20),active=true where id=pid; return query select p.id,p.balance from love_players p where p.id=pid; return; end if;
 if (select count(*) from love_players where room_id=rid and active=true)>=11 then raise exception '房间已满'; end if;
 insert into love_players(room_id,name,token,active) values(rid,left(trim(p_name),20),p_token,true) returning id into pid;
 return query select p.id,p.balance from love_players p where p.id=pid;
end $$;

create or replace function public.love_leave_room(p_room_id text,p_player_token text) returns void language plpgsql security definer set search_path=public as $$ begin update love_players set active=false where room_id=upper(p_room_id) and token=p_player_token; end $$;

create or replace function public.love_start_lot(p_room_id text,p_host_secret text,p_lot_id integer) returns void language plpgsql security definer set search_path=public as $$
begin
 if p_lot_id<1 or p_lot_id>30 then raise exception '拍品编号无效'; end if;
 if exists(select 1 from love_wins where room_id=upper(p_room_id) and lot_id=p_lot_id) then raise exception '该拍品已经成交'; end if;
 update love_rooms set current_lot=p_lot_id,status='open',current_bid=null,current_bidder=null,current_bidder_name=null where id=upper(p_room_id) and host_secret=p_host_secret;
 if not found then raise exception '主持人权限无效'; end if;
end $$;

create or replace function public.love_place_bid(p_room_id text,p_player_token text,p_amount bigint) returns void language plpgsql security definer set search_path=public as $$
declare r love_rooms%rowtype; p love_players%rowtype; v_min bigint; begin
 select * into r from love_rooms where id=upper(p_room_id) for update; if not found then raise exception '房间不存在'; end if;
 if r.status<>'open' or r.current_lot is null then raise exception '当前没有开放竞拍'; end if;
 select * into p from love_players where room_id=r.id and token=p_player_token and active=true; if not found then raise exception '玩家身份无效'; end if;
 v_min:=coalesce(r.current_bid+1000000,1000000);
 if p_amount<v_min then raise exception '最低有效出价为 % 万',v_min/10000; end if;
 if mod(p_amount,1000000)<>0 then raise exception '出价必须按100万递增'; end if;
 if p_amount>p.balance then raise exception '余额不足'; end if;
 update love_rooms set current_bid=p_amount,current_bidder=p.id,current_bidder_name=p.name where id=r.id;
end $$;

create or replace function public.love_close_lot(p_room_id text,p_host_secret text) returns void language plpgsql security definer set search_path=public as $$
declare r love_rooms%rowtype; p love_players%rowtype; begin
 select * into r from love_rooms where id=upper(p_room_id) for update; if not found or r.host_secret<>p_host_secret then raise exception '主持人权限无效'; end if;
 if r.status<>'open' or r.current_bidder is null then raise exception '当前没有可成交的竞价'; end if;
 select * into p from love_players where id=r.current_bidder for update; if p.balance<r.current_bid then raise exception '赢家余额不足'; end if;
 update love_players set balance=balance-r.current_bid where id=p.id;
 insert into love_wins(room_id,lot_id,player_id,player_name,price) values(r.id,r.current_lot,p.id,p.name,r.current_bid);
 update love_rooms set status='closed' where id=r.id;
end $$;

create or replace function public.love_pass_lot(p_room_id text,p_host_secret text) returns void language plpgsql security definer set search_path=public as $$ begin update love_rooms set status='closed' where id=upper(p_room_id) and host_secret=p_host_secret; if not found then raise exception '主持人权限无效'; end if; end $$;

create or replace function public.love_get_host_state(p_room_id text,p_host_secret text) returns jsonb language plpgsql security definer set search_path=public as $$
declare r love_rooms%rowtype; result jsonb; begin
 select * into r from love_rooms where id=upper(p_room_id) and host_secret=p_host_secret; if not found then raise exception '主持人权限无效或房间不存在'; end if;
 select jsonb_build_object('room',(to_jsonb(r)-'host_secret'),'players',coalesce((select jsonb_agg(jsonb_build_object('id',p.id,'name',p.name,'balance',p.balance,'joined_at',p.joined_at) order by p.joined_at) from love_players p where p.room_id=r.id and p.active=true),'[]'::jsonb),'wins',coalesce((select jsonb_agg(jsonb_build_object('id',w.id,'room_id',w.room_id,'lot_id',w.lot_id,'player_id',w.player_id,'player_name',w.player_name,'price',w.price,'created_at',w.created_at) order by w.created_at desc) from love_wins w where w.room_id=r.id),'[]'::jsonb)) into result; return result;
end $$;

create or replace function public.love_get_player_state(p_room_id text,p_player_token text) returns jsonb language plpgsql security definer set search_path=public as $$
declare r love_rooms%rowtype; p love_players%rowtype; result jsonb; begin
 select * into r from love_rooms where id=upper(p_room_id); if not found then raise exception '房间不存在'; end if;
 select * into p from love_players where room_id=r.id and token=p_player_token limit 1; if not found then raise exception '玩家身份无效，请重新加入'; end if;
 select jsonb_build_object('room',(to_jsonb(r)-'host_secret'),'player',jsonb_build_object('id',p.id,'name',p.name,'balance',p.balance,'joined_at',p.joined_at,'active',p.active),'wins',coalesce((select jsonb_agg(jsonb_build_object('id',w.id,'lot_id',w.lot_id,'price',w.price,'created_at',w.created_at) order by w.created_at desc) from love_wins w where w.room_id=r.id and w.player_id=p.id),'[]'::jsonb)) into result; return result;
end $$;

grant execute on function public.love_create_room(text,text) to anon,authenticated;
grant execute on function public.love_join_room(text,text,text) to anon,authenticated;
grant execute on function public.love_leave_room(text,text) to anon,authenticated;
grant execute on function public.love_start_lot(text,text,integer) to anon,authenticated;
grant execute on function public.love_place_bid(text,text,bigint) to anon,authenticated;
grant execute on function public.love_close_lot(text,text) to anon,authenticated;
grant execute on function public.love_pass_lot(text,text) to anon,authenticated;
grant execute on function public.love_get_host_state(text,text) to anon,authenticated;
grant execute on function public.love_get_player_state(text,text) to anon,authenticated;
grant select on public.love_rooms,public.love_players,public.love_wins to anon,authenticated;
alter table public.love_rooms disable row level security; alter table public.love_players disable row level security; alter table public.love_wins disable row level security;
do $$ begin begin alter publication supabase_realtime add table public.love_rooms; exception when duplicate_object then null; end; begin alter publication supabase_realtime add table public.love_players; exception when duplicate_object then null; end; begin alter publication supabase_realtime add table public.love_wins; exception when duplicate_object then null; end; end $$;
