
-- 人生拍卖会：Supabase 数据库初始化
-- 在 Supabase -> SQL Editor 中一次性执行本文件。

create extension if not exists pgcrypto;

create table if not exists public.rooms (
  id text primary key,
  host_secret text not null,
  current_lot integer,
  status text not null default 'waiting' check (status in ('waiting','open','closed')),
  current_bid bigint,
  current_bidder uuid,
  current_bidder_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.players (
  id uuid primary key default gen_random_uuid(),
  room_id text not null references public.rooms(id) on delete cascade,
  name text not null,
  token text not null unique,
  balance bigint not null default 150000000 check (balance >= 0),
  joined_at timestamptz not null default now()
);

create table if not exists public.wins (
  id bigint generated by default as identity primary key,
  room_id text not null references public.rooms(id) on delete cascade,
  lot_id integer not null,
  player_id uuid not null references public.players(id) on delete cascade,
  player_name text not null,
  price bigint not null,
  created_at timestamptz not null default now(),
  unique(room_id, lot_id)
);

create or replace function public.create_room(p_room_id text, p_host_secret text)
returns void language plpgsql security definer set search_path=public as $$
begin
  if length(p_room_id) < 4 or length(p_host_secret) < 16 then raise exception 'invalid room'; end if;
  insert into rooms(id,host_secret) values(upper(p_room_id),p_host_secret);
end $$;

create or replace function public.join_room(p_room_id text, p_name text, p_token text)
returns table(player_id uuid, balance bigint)
language plpgsql security definer set search_path=public as $$
declare pid uuid;
begin
  if not exists(select 1 from rooms where id=upper(p_room_id)) then raise exception '房间不存在'; end if;
  if char_length(trim(p_name)) < 1 then raise exception '请输入昵称'; end if;
  if (select count(*) from players where room_id=upper(p_room_id)) >= 11 then raise exception '房间已满'; end if;
  insert into players(room_id,name,token) values(upper(p_room_id),left(trim(p_name),20),p_token)
  returning id into pid;
  return query select p.id,p.balance from players p where p.id=pid;
end $$;

create or replace function public.start_lot(p_room_id text, p_host_secret text, p_lot_id integer)
returns void language plpgsql security definer set search_path=public as $$
begin
  update rooms set current_lot=p_lot_id,status='open',current_bid=null,current_bidder=null,current_bidder_name=null
  where id=upper(p_room_id) and host_secret=p_host_secret;
  if not found then raise exception '主持人权限无效'; end if;
  if exists(select 1 from wins where room_id=upper(p_room_id) and lot_id=p_lot_id) then raise exception '该拍品已经成交'; end if;
end $$;

create or replace function public.place_bid(p_room_id text, p_player_token text, p_amount bigint)
returns void language plpgsql security definer set search_path=public as $$
declare r rooms%rowtype; p players%rowtype; v_start bigint; v_step bigint; v_min bigint;
begin
  select * into r from rooms where id=upper(p_room_id) for update;
  if not found then raise exception '房间不存在'; end if;
  if r.status <> 'open' or r.current_lot is null then raise exception '当前没有开放竞拍'; end if;
  select * into p from players where room_id=r.id and token=p_player_token;
  if not found then raise exception '玩家身份无效'; end if;

  if r.current_lot <= 20 then v_start:=1000000; v_step:=500000;
  elsif r.current_lot <= 40 then v_start:=2000000; v_step:=1000000;
  elsif r.current_lot <= 50 then v_start:=5000000; v_step:=1000000;
  else v_start:=10000000; v_step:=2000000;
  end if;
  v_min:=coalesce(r.current_bid+v_step,v_start);

  if p_amount < v_min then raise exception '出价低于最低有效价格'; end if;
  if p_amount > p.balance then raise exception '余额不足'; end if;

  update rooms set current_bid=p_amount,current_bidder=p.id,current_bidder_name=p.name where id=r.id;
end $$;

create or replace function public.close_lot(p_room_id text, p_host_secret text)
returns void language plpgsql security definer set search_path=public as $$
declare r rooms%rowtype; p players%rowtype;
begin
  select * into r from rooms where id=upper(p_room_id) for update;
  if not found or r.host_secret<>p_host_secret then raise exception '主持人权限无效'; end if;
  if r.status<>'open' or r.current_bidder is null then raise exception '当前没有可成交的竞价'; end if;
  select * into p from players where id=r.current_bidder for update;
  if p.balance<r.current_bid then raise exception '赢家余额不足'; end if;
  update players set balance=balance-r.current_bid where id=p.id;
  insert into wins(room_id,lot_id,player_id,player_name,price) values(r.id,r.current_lot,p.id,p.name,r.current_bid);
  update rooms set status='closed' where id=r.id;
end $$;

create or replace function public.pass_lot(p_room_id text, p_host_secret text)
returns void language plpgsql security definer set search_path=public as $$
begin
  update rooms set status='closed' where id=upper(p_room_id) and host_secret=p_host_secret;
  if not found then raise exception '主持人权限无效'; end if;
end $$;

grant execute on function public.create_room(text,text) to anon;
grant execute on function public.join_room(text,text,text) to anon;
grant execute on function public.start_lot(text,text,integer) to anon;
grant execute on function public.place_bid(text,text,bigint) to anon;
grant execute on function public.close_lot(text,text) to anon;
grant execute on function public.pass_lot(text,text) to anon;

grant select on public.rooms to anon;
grant select on public.players to anon;
grant select on public.wins to anon;

-- 聚会原型：为方便实时读取，暂不启用 RLS。
alter table public.rooms disable row level security;
alter table public.players disable row level security;
alter table public.wins disable row level security;

do $$
begin
  begin alter publication supabase_realtime add table public.rooms; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.players; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.wins; exception when duplicate_object then null; end;
end $$;
